databases:
  - name: helpdesk
    databaseName: helpdesk
    user: helpdesk
    plan: free

services:
  - type: web
    name: helpdesk
    env: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: helpdesk
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis
          property: connectionString
  - type: redis
    name: redis
    ipAllowList: []
    plan: free
    maxmemoryPolicy: noeviction